trigger: none

variables:
- template: steps/variables.yml
- name: ResourceGroupName
  value: publisher-mqtt-k8s
- name: Region
  value: northeurope
- name: Cleanup
  value: false
- name: PublisherImagePath
  value: mqtt-publisher
     

stages:
# build test resource
# upload test resource

- stage: deployAKS
  displayName: "Deploy AKS"
  jobs:
  - job: deployaks
    displayName: 'Deploy aks cluster'
    timeoutInMinutes: 180
    steps: 
    - template: steps/deployaks.yml

# run tests

- stage: cleanup
  displayName: Cleanup resources
  dependsOn: deployAKS
  condition: and(not(canceled()), eq(variables['Cleanup'], true))
  jobs:
  - job: cleanup
    displayName: Cleanup
    steps:
    - template: steps/cleanupaks.yml
      parameters:
        CleanupAppRegistrations: false