variables:
- template: steps/variables.yml
- name: ResourceGroupName
  value: jscakse2e
- name: Region
  value: northeurope
   

stages:
# - stage: deploy
#   displayName: "Deploy IoT Hub and Key Vault"
  
#   jobs:
#   - job: deploystandalone
#     displayName: 'Deploy Standalone Resources'
#     steps:
#     - template: steps/deploystandalone.yml

#build test resource
# upload test resource

- stage: deployAKS
  displayName: "Deploy AKS"
  #dependsOn: deploy
  #condition: and(not(canceled()), eq(dependencies.deploy.result, 'Succeeded'))
  jobs:
  - job: deployaks
    displayName: 'Deploy aks cluster'
    timeoutInMinutes: 180
    steps: 
    - template: steps/deployaks.yml

# runt tests

- stage: cleanup
  displayName: Cleanup resources
  dependsOn: deployAKS
  condition: and(not(canceled()), eq(variables['Cleanup'], true))
  jobs:
  - job: cleanup
    displayName: Cleanup
    steps:
    - template: steps/cleanup.yml
      parameters:
        CleanupAppRegistrations: false